// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SANATORIO_HIPOCRATES.Config;

namespace SANATORIO_HIPOCRATES.Migrations
{
    [DbContext(typeof(Conexion))]
    [Migration("20230618033331_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("SANATORIO_HIPOCRATES.Entidades.Persona", b =>
                {
                    b.Property<long>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("IdPersona");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("SANATORIO_HIPOCRATES.Entidades.Turno", b =>
                {
                    b.Property<long>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdTurno");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("SANATORIO_HIPOCRATES.Entidades.Empleado", b =>
                {
                    b.HasBaseType("SANATORIO_HIPOCRATES.Entidades.Persona");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdEmpleado")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<double>("Salario")
                        .HasColumnType("double");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Empleado");
                });

            modelBuilder.Entity("SANATORIO_HIPOCRATES.Entidades.Paciente", b =>
                {
                    b.HasBaseType("SANATORIO_HIPOCRATES.Entidades.Persona");

                    b.Property<long>("IdPaciente")
                        .HasColumnType("bigint");

                    b.Property<long>("NumeroCarnet")
                        .HasColumnType("bigint");

                    b.Property<string>("ObraSocial")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("SANATORIO_HIPOCRATES.Entidades.Medico", b =>
                {
                    b.HasBaseType("SANATORIO_HIPOCRATES.Entidades.Empleado");

                    b.Property<string>("Especialidad")
                        .HasColumnType("longtext");

                    b.Property<long>("IdMedico")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Medico");
                });

            modelBuilder.Entity("SANATORIO_HIPOCRATES.Entidades.Recepcionista", b =>
                {
                    b.HasBaseType("SANATORIO_HIPOCRATES.Entidades.Empleado");

                    b.Property<long>("IdRecepcionista")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Recepcionista");
                });
#pragma warning restore 612, 618
        }
    }
}
